### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by stephenhuey** [paulvanbladel/aurelia-auth#88]
Per the README, I'm trying to install aurelia-auth with the latest ES6 skeleton for Aurelia.  Is your README up-to-date on how to install with jspm?  

https://auth0.com/blog/2015/08/05/creating-your-first-aurelia-app-from-authentication-to-calling-an-api/

Ryan Chenkie's blog post on August 5th suggests using 

jspm install github:paulvanbladel/aurelia-auth

but I don't want to do that if it's not the best way.  I'm doing this in a new project because I'm trying to get aurelia-auth to be accessible in the output from the Aurelia skeleton's gulp bundle, so I'm really trying to use the right paths since various old tutorials differ between using paulvanbladel/aurelia-auth and aurelia-auth in the Aurelia import statements.  Here's what I did on my command line just now with the latest Aurelia ES6 skeleton:  

$ jspm install aurelia-auth 

err  TypeError: Install of aurelia-bootstrapper to ^0.9.1 has no registry property provided.
         at /Users/stephen/code/admin-new-front/node_modules/jspm/lib/package.js:309:13
         at Array.forEach (native)
         at processDeps (/Users/stephen/code/admin-new-front/node_modules/jspm/lib/package.js:292:21)
         at setDefaults (/Users/stephen/code/admin-new-front/node_modules/jspm/lib/config/package.js:128:25)
         at PackageJSON.read (/Users/stephen/code/admin-new-front/node_modules/jspm/lib/config/package.js:116:3)
         at /Users/stephen/code/admin-new-front/node_modules/jspm/lib/config.js:80:25
         at process._tickCallback (node.js:368:9)
         at Function.Module.runMain (module.js:469:11)
         at startup (node.js:136:18)
         at node.js:963:3

warn Installation changes not saved.

**Comment by RWOverdijk** [comment]
Does this mean you figured it out? :)
